// Mocks generated by Mockito 5.4.2 from annotations
// in server_alerts/test/bloc/alert_builder_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/widgets.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:server/server.dart' as _i2;
import 'package:server_alerts/models/alert.dart' as _i5;
import 'package:server_alerts/repository/alert_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServiceConnection_0 extends _i1.SmartFake
    implements _i2.ServiceConnection {
  _FakeServiceConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_1<T> extends _i1.SmartFake
    implements _i3.ValueNotifier<T> {
  _FakeValueNotifier_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AlertsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertsRepository extends _i1.Mock implements _i4.AlertsRepository {
  MockAlertsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ServiceConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeServiceConnection_0(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i2.ServiceConnection);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: '',
      ) as String);

  @override
  _i3.ValueNotifier<List<_i5.PriceAlert>> get alertsNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#alertsNotifier),
        returnValue: _FakeValueNotifier_1<List<_i5.PriceAlert>>(
          this,
          Invocation.getter(#alertsNotifier),
        ),
      ) as _i3.ValueNotifier<List<_i5.PriceAlert>>);

  @override
  set isInitialized(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isInitialized,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<dynamic> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  bool isInitialize() => (super.noSuchMethod(
        Invocation.method(
          #isInitialize,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<dynamic> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<void> sendAlert(
    String? pair,
    double? currentPrice,
    _i5.PriceAlert? alert,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAlert,
          [
            pair,
            currentPrice,
            alert,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadAlerts(
    String? pair, [
    int? maxCount = 100,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAlerts,
          [
            pair,
            maxCount,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeAlert(_i5.PriceAlert? alert) => (super.noSuchMethod(
        Invocation.method(
          #removeAlert,
          [alert],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAllAlerts() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllAlerts,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
